### ISSUE TITLE
Default Enums error

### ISSUE THREAD

**Issue by slamservice** [andrewdwallo/erpsaas#24]
I’m trying to install the new version of erpsaas and I get an error on 
    public const DEFAULT = self::Indigo->value;
I’m using php 8.1: can this be the problem?

The error is: constant expression contains invalid operations

**Comment by slamservice** [comment]
yes, the problem is the php version. It takes 8.2

**Comment by andrewdwallo** [comment]
@slamservice Yes PHP 8.2 is required for this. If that is a big problem, then you may remove them and find all of the instances of the `Enum::DEFAULT` constants and replace them. Sorry about that, but I wouldn't think it would be a big deal and the PHP version in `composer.json` says 8.2.
