### ISSUE TITLE
filament/packages/* URL

### ISSUE THREAD

**Issue by abdelrahman-mohamed120** [andrewdwallo/erpsaas#26]
I have a issue after make a composer install 
{Problem 1     
  - Root composer.json requires php ^8.2 but your php version (8.1.12) does not satisfy that requirement. 
after make composer update 
 -The `url` supplied for the path (filament/packages/*) repository does not exist  
![image](https://github.com/andrewdwallo/erpsaas/assets/76571972/d7b127f9-e564-48ff-aeb0-2e0288fae42b)

**Comment by andrewdwallo** [comment]
Apologies, I am not even sure when that was committed. I will update the repository soon and let you know. As for the PHP version, PHP 8.2 is required.

**Comment by andrewdwallo** [comment]
Thank you for letting me know.

**Comment by andrewdwallo** [comment]
@abdelrhmanMohmaed If you have a fork, please sync the latest update and update your application. After that, please let me know if everything works correctly. Thanks!

If you still get errors after doing that, you may have to run the following:
```shell
rm -rf vendor composer.lock
```
and then:
```shell
composer update
```

**Comment by andrewdwallo** [comment]
Commit: https://github.com/andrewdwallo/erpsaas/commit/ea3d62e035facdcf3da8370ba0cc1d41202dade4
