### ISSUE TITLE
URL not found

### ISSUE THREAD

**Issue by samee-sys** [andrewdwallo/erpsaas#28]
I installed without any error and able to access welcome page. When I click on login or any other page, it is giving 'The requested URL was not found on this server.' I am using php 8.2. I looked in adminpanelprovider and tried to access admin path, but same results.
![image](https://github.com/andrewdwallo/erpsaas/assets/58465165/f299b624-0584-4bc7-85c0-09c335269c0a)

**Comment by andrewdwallo** [comment]
I have no clue what the issue is, but it has nothing to do with this application. This is something wrong with your server. Maybe it is configured incorrectly. Do some research.

**Comment by andrewdwallo** [comment]
One more thing to note. There is nothing inside the Admin Panel worth looking at yet. The main panel is the company panel.

**Comment by Medsek233** [comment]
same problem url not found

**Comment by mszabeh** [comment]
same problem url not found

**Comment by Medsek233** [comment]
do php artisan serve and it will work

**Comment by mszabeh** [comment]
> do php artisan serve and it will work

tnx Mohammad.
but why not work without php artisan serve
😉

**Comment by andrewdwallo** [comment]
@mszabeh Are you using Apache perchance? Is anyone here who is having the issue using Apache?

**Comment by mszabeh** [comment]
@andrewdwallo 
yes, I am using Apache.

**Comment by andrewdwallo** [comment]
@mszabeh Use Nginx instead and let me know how that works for you. I think that should fix it.

**Comment by mszabeh** [comment]
I am using in laragon (in local) and I don't have nginx setup in my system right now.
Now, I am using php artisan serve in Apache and use the erpsaas.

**Comment by andrewdwallo** [comment]
Okay well whatever works for you but I believe setting up Nginx in Laragon is pretty easy.

**Comment by andrewdwallo** [comment]
Someone seems to have possibly found the solution for those of you who are experiencing a similar issue. I encourage you to give it a try and report back your results. Thanks! https://github.com/andrewdwallo/erpsaas/discussions/1#discussioncomment-7537349
