### ISSUE TITLE
Problem with yarn run dev

### ISSUE THREAD

**Issue by Odilbukh** [andrewdwallo/erpsaas#3]
All other commands runs good but command yarn run dev returns error like :

`
yarn run v1.22.19
$ vite
file:///media/asus/DiskD/OpenServer/domains/erpsaas/node_modules/vite/bin/vite.js:7
    await import('source-map-support').then((r) => r.default.install())
    ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

`

And of course http://127.0.0.1:8000/admin/login shows error like:

`
Vite manifest not found at: /media/asus/DiskD/OpenServer/domains/erpsaas/public/build/manifest.json
` 

What to do? Please help to fix it

**Comment by andrewdwallo** [comment]
Are you installing everything in the correct order?  And from what is looks like:
You put: http://127.0.0.1:8000/admin/login
Make sure you are setting your APP_URL when using "yarn run dev" command...
For me it is https://erpsaas.test or https://erpsaas.dev for example.. 
If you want to use your localhost in the APP_URL then you need to use the "php artisan serve" command
