### ISSUE TITLE
Invoice to PDF

### ISSUE THREAD

**Issue by sasaorasanin** [andrewdwallo/erpsaas#38]
Hello, did you maybe try to generate an invoice design to PDF? 

I may be wrong, but when I tried it couldnt get any of tailwind css, so I added all into inline styles, where I needed to change a lot structure to tables with inline styles. Also, could not remove margins/padding fully..

Looks a bit different from tailwind ones, but if you tried maybe you can share what you used?

I used barryvdh/laravel-dompdf... It is quite slow when generating PDF with images..

Thanks

**Comment by andrewdwallo** [comment]
The invoices you see currently are invoice previews. They are only a representation of what the final invoice would look like. This is only for settings and configuration of what the company wants for their invoice to look like. What you mentioned will be added later. I heard dompdf isn't the best to use either and I have heard of similar things that could use tailwindcss, but I forgot the names of them.

**Comment by andrewdwallo** [comment]
Please use discussions section for questions like this next time. Thanks.
