### ISSUE TITLE
Personal Access Tokens API not working as expected

### ISSUE THREAD

**Issue by wejrcze** [andrewdwallo/erpsaas#39]
Hello,
I'm trying to get API working, but i still get:
`
{
    "message": "Unauthenticated."
}
`

Can't find any information if it's implemented by default, o I have to implement it myself, thank you Andrew for your help.

**Comment by andrewdwallo** [comment]
The settings for sanctum probably need to be configured for your environment properly. I would make sure to follow all of the instructions [here](https://laravel.com/docs/10.x/sanctum#cors-and-cookies) carefully.

**Comment by wejrcze** [comment]
> The settings for sanctum probably need to be configured for your environment properly. I would make sure to follow all of the instructions [here](https://laravel.com/docs/10.x/sanctum#cors-and-cookies) carefully.

Thank you, already managed that in Authenticate middleware(which only counts with web guard), where I auths sanctum guard properly ( /api/{panel}/{tenant}/route...

**Comment by andrewdwallo** [comment]
Okay sounds good! No problem.
