### ISSUE TITLE
Attempt to read property "name" on null in Manage Company

### ISSUE THREAD

**Issue by zxstudio-llc** [andrewdwallo/erpsaas#50]

**Comment by andrewdwallo** [comment]
Providing only your error message doesn't really help me track down what the issue could be. Can you provide more context on when this error occurs? Can you provide the stacktrace for me? Is this error with the latest release? Everything is working perfectly fine for me when visiting the "Manage Company" page. Have you created a company? If you have created a company, is the "name" column in the database null even though you provided a name when creating one?

**Comment by zxhub-llc** [comment]
I'm sorry, I managed to solve it, apparently when making the changes and migrations something was not done correctly with my db but I executed the php artisan migrate:fresh command and it was solved
