### ISSUE TITLE
URL Not Found

### ISSUE THREAD

**Issue by Fik21-i** [andrewdwallo/erpsaas#51]
![Screenshot 2024-05-26 094218](https://github.com/andrewdwallo/erpsaas/assets/99479302/ac3bcf78-2aea-47e6-8fd2-9ce260ace7b9)
![Screenshot 2024-05-26 094205](https://github.com/andrewdwallo/erpsaas/assets/99479302/be19a9d2-9a2a-4d59-925d-6944bfda6a66)

hi , i already follow all the installation instruction . im using Laragon . but after installation , once i try to open the url . its 404 . is that from my part or other things?

**Comment by andrewdwallo** [comment]
Everything is working fine for me. This is probably an issue with either your server or your Laragon settings.

**Comment by andrewdwallo** [comment]
@Fik21-i Did you find the issue?

**Comment by Fik21-i** [comment]
Sorry for my late reply. I need to run php artisan serve in order to application run in web . I think its problem from my side . Thanks again
