### ISSUE TITLE
Error while seeding database

### ISSUE THREAD

**Issue by pratikkuikel** [andrewdwallo/erpsaas#55]
Steps to reproduce : 
1. Clone the repo
2. Run composer, npm, publish filament assets, run npm dev server
3. Set database as sqlite
4. Generate key and run the migrations

Command : php artisan db:seed

```php
 TypeError 

  App\Observers\TransactionObserver::convertToDefaultCurrency(): Argument #2 ($fromCurrency) must be of type string, null given, called in C:\Users\prati\OneDrive\Desktop\erpsaas\app\Observers\TransactionObserver.php on line 114

  at app\Observers\TransactionObserver.php:122
    118▕
    119▕         return $transaction->amount;
    120▕     }
    121▕
  ➜ 122▕     private function convertToDefaultCurrency(string $amount, string $fromCurrency, string $toCurrency): string    123▕     {
    124▕         $amountInCents = CurrencyConverter::prepareForAccessor($amount, $fromCurrency);
    125▕
    126▕         $convertedAmountInCents = CurrencyConverter::convertBalance($amountInCents, $fromCurrency, $toCurrency);

  1   app\Observers\TransactionObserver.php:114
      App\Observers\TransactionObserver::convertToDefaultCurrency("2,638.00", "USD")

  2   app\Observers\TransactionObserver.php:88
      App\Observers\TransactionObserver::getConvertedTransactionAmount(Object(App\Models\Accounting\Transaction)) 
```

**Comment by Subeen928** [comment]
Got same issue.

**Comment by andrewdwallo** [comment]
It's weird that I didn't get this issue. Are both of yall using SQLite?

**Comment by andrewdwallo** [comment]
Put the "silent()" method on the Transaction creation in the User factory and let me know if that helps.

**Comment by andrewdwallo** [comment]
Both of you please update to latest release or try the logic mentioned in the new release and let me know if that fixes your issue. Thanks.

**Comment by andrewdwallo** [comment]
I'm actually going to have to revert the latest release because this changes accurate report data. I will need to investigate.

**Comment by pratikkuikel** [comment]
> It's weird that I didn't get this issue. Are both of yall using SQLite?

Yesh, It's sqlite.

**Comment by andrewdwallo** [comment]
@pratikkuikel So the issue was only occurring when using SQLite? When using MySQL the error did not occur for you? Is everything working for you now on the latest release?

**Comment by pratikkuikel** [comment]
The previous release with issue, I didn't try that with mysql.
But I can confirm that the latest release works fine with mysql too.
yes, the issue is no longer present in sqlite after pulling in the latest release.
