### ISSUE TITLE
account and transaction page 

### ISSUE THREAD

**Issue by Subeen928** [andrewdwallo/erpsaas#58]
TypeError:
App\ValueObjects\Money::__construct(): Argument #2 ($currencyCode) must be of type string, null given, called in /home/subin_928/Desktop/erpsaas/app/Services/AccountService.php on line 65

**Comment by andrewdwallo** [comment]
@Subeen928 You are going to have to give me more information regarding the issue if you want me to address it. 

- How to reproduce the issue?
- What were you doing when the exception occurred?
- Does your account have a currency code?

**Comment by andrewdwallo** [comment]
Run `php artisan migrate:fresh`, run your seeder, and then get back to me.

**Comment by mavrickdeveloper** [comment]
having same issue , fresh migrate run but the problem insist

![Screenshot 2024-07-14 191237](https://github.com/user-attachments/assets/dcb2d87d-1532-494a-82f7-5bc4d6710a9d)

**Comment by Subeen928** [comment]
@andrewdwallo It works fine now, (I re-pull the repo from the git)  .. 
Thanks!!
