### ISSUE TITLE
Error when install enviroment

### ISSUE THREAD

**Issue by DUC-ANH-LY** [andrewdwallo/erpsaas#67]
when I install this project by readme guideline, I'm face this problem
![image](https://github.com/user-attachments/assets/12682259-ba70-4a51-8280-7ee68272aabe)

**Comment by andrewdwallo** [comment]
The table is cached in memory using SQLite. Look at the squire documentation.

**Comment by DUC-ANH-LY** [comment]
@andrewdwallo Thank you for your supporting , I resolved that by delete squire cache file in `storage/framework/cache`
