### ISSUE TITLE
Create Sales Invoice

### ISSUE THREAD

**Issue by vinnchan** [andrewdwallo/erpsaas#74]
Hi, thank you for your contributions, correct me if I am wrong, we are able to see the invoice template setting but not the module to create sales invoice, how can we create sales invoice ? 
Thanks

**Comment by andrewdwallo** [comment]
@vinnchan The feature hasn't been created yet. It's coming up next on the list though after I'm finished adding all of the financial statements/reports.

Please create a discussion post next time since this is not a bug or issue.
