### ISSUE TITLE
Accessing Accounts in Banking Category gives error

### ISSUE THREAD

**Issue by faizanakbar10** [andrewdwallo/erpsaas#82]
The following error occurs for fresh installation of project without DB seeding.

Login -> Accounts

<img width="1327" alt="Screenshot 2024-12-03 at 1 28 15 PM" src="https://github.com/user-attachments/assets/8bcb9e5d-782a-4e55-b912-3e18fdb29108">

Similarly for any Reports; Income statement, Balance Sheet etc.

**Comment by andrewdwallo** [comment]
Should be fixed in the latest release. Let me know if you have any issues. Thanks.
